django_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("MainApp.urls")),
    path('vendor/', include('shop.urls'), name='vendor'),
    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('sign_up', views.sign_up, name='sign_up'),
    path('login', views.login, name='login'),
    path('otp_verification', views.login, name='otp_verification'),
    path('', views.vendor_home, name='vendor_home'),
    path('vedor_products/', views.vendor_products, name='vendor_products'),
    path('add_product/', views.add_product, name='add_product'),
    path('edit_product/<str:product>', views.edit_product, name='edit_product'),
    path('logout', views.log_out, name='log_out'),
    path('vendor_profile', views.profile, name='vendor_profile'),
    path('shop_orders', views.shop_orders, name='shop_orders')
 
]

shop/models.py
from django.db import models

# Create your models here.
from django.urls import reverse

class Vendor(models.Model):
    shop_name = models.TextField(max_length=50)
    mobile_number = models.CharField(max_length=10, primary_key=True)
    password = models.TextField(max_length=50)
    pincode = models.IntegerField()
    otp = models.IntegerField(null=True, default=None, blank=True)
    is_verified = models.BooleanField(default=False)
    shop_image = models.ImageField(upload_to="shops/", null=True, blank=True)

    def __str__(self) -> str:
        return self.shop_name



class ProductCategory(models.Model):
    category = models.TextField(max_length=50)

    def __str__(self) -> str:
        return self.category
    
class Product(models.Model):
    product_name = models.TextField(max_length=50, primary_key=True)
    product_price = models.IntegerField()
    product_category = models.ForeignKey(ProductCategory, on_delete=models.SET_NULL, null=True, blank=True)
    product_details = models.TextField(max_length=100)
    product_image = models.ImageField(upload_to="products/")
    shop = models.ForeignKey(Vendor, on_delete=models.CASCADE)
    product_quantity = models.IntegerField(default=0)

    def get_absolute_url(self):
        return self.product_name


    def __str__(self) -> str:
        return self.product_name

templates/add_product.html
{% extends 'base.html' %}


{% block head %}

<title>Vendor | Add Product</title>

<style>
    .custom-container {
      display: flex;
      align-items: center;
      margin: 2%;
      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.4);
      padding: 2%;
      background-color: rgb(253, 249, 249);
    }
  
    .custom-input {
      margin-bottom: 10px;
    }
  
    .add-product:hover {
      background-color: rgb(9, 235, 122);

    }

    

    

  </style>

{% endblock %}



{% block body %}

{% for message in messages %}

<p style="color: green;">{{ message }}</p>

{% endfor %}


<div class="custom-container">
    <a href="{% url 'vendor_products' %}" class="btn btn-primary go-back"> <b><--</b> Go Back to Products</a>
    <form class="w-75 mx-auto" action="{% url 'add_product' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group row">
            <label for="product_name" class="col-sm-2 col-form-label">Product Name</label>
            <div class="col-sm-10">
                <input type="text" name="product_name" class="form-control custom-input" id="product_name" required>
            </div>
        </div>

        <div class="form-group row">
            <label for="product_price" class="col-sm-2 col-form-label">Price</label>
            <div class="col-sm-10">
                <input type="number" name="product_price" id="product_price" class="form-control custom-input" min="1" required>
            </div>
        </div>

        <div class="form-group row">
            <label for="product_category" class="col-sm-2 col-form-label">Product Category</label>
            <div class="col-sm-10">
                <select name="product_category" id="product_category" class="form-control custom-input" required>
                    <!--Add product category from ProductCategory models-->

                    <!--Add product category from ProductCategory models-->
                    {% for category in categories %}

                    <option value={{category.category }}>{{ category.category }}</option>

                    {% endfor %}



                </select> <br>
            </div>
        </div>

        <div class="form-group row">
            <label for="product_detail" class="col-sm-2 col-form-label">Product Details</label>
            <div class="col-sm-10">
                <textarea type="text" name="product_detail" id="product_detail" cols="30" rows="10"
                    class="form-control custom-input"></textarea>
            </div>
        </div>

        <div class="form-group row">
            <label for="id_product_image" class="col-sm-2 col-form-label">Product Image</label>
            <div class="col-sm-10">
                <input type="file" name="product_image" accept="image/*" id="id_product_image"
                    class="form-control custom-input" required>
            </div>
        </div>

        <div class="form-group row">

            <div class="col-sm-12 ">
                <input type="submit" value="Add Product" class="form-control add-product custom-input">
            </div>
        </div>
    </form>
</div>



<!-- <form action="{% url 'add_product' %}" method="post" enctype="multipart/form-data">

        {% csrf_token %}
        <label for="product_name">Product Name</label>
        <input type="text" name="product_name" id="product_name"> <br>

        <label for="product_price">Product Price</label>
        <input type="text" name="product_price" id="product_price"> <br>
        
        <label for="product_category">Choose a Product Category:</label>
        <select name="product_category" id="product_category"> -->
<!--Add product category from ProductCategory models-->
<!-- {% for category in categories %}

          <option value={{category.category }}>{{ category.category }}</option>

         {% endfor %}
        </select> <br>

        <label for="product_detail">Product Details</label>
        <textarea name="product_detail" id="product_detail" cols="30" rows="10"></textarea> <br>

        <label for="id_product_image">Proudct Image</label>
          
        <input type="file" name="product_image" accept="image/*" required="" id="id_product_image"> <br>

        <input type="submit" value="Add Product">

    </form> -->








{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <style>

        body {
            background-color: #eae7e1;
        }

    </style>


    {% block head %}



    {% endblock %}

</head>

<body>

    {% block nav %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">


            <a class="navbar-brand" href="{% url 'vendor_home' %}">Direct Store</a>


            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'shop_orders' %}">Orders</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'vendor_products' %}">Update Products</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'add_product' %}">Add Product</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'vendor_profile' %}"> Profile</a>
                    </li>

                    <!-- <li class="nav-item">
                        <a class="nav-link active"  href="#">Profile</a>
                    </li> -->

                    

                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'log_out' %}">Log out</a>
                    </li>
                   
                </ul>
            </div>
        </div>
    </nav>

    {% endblock %}

    


    {% block body %}



    {% endblock %}



</body>

   

</html>

templates/edit_product.html
{% extends 'base.html' %}


{% block head %}

<title>Vendor | Edit Product</title>

<style>
  .custom-container {
    display: flex;
    align-items: center;
    margin: 2%;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
    padding: 2%;
  }

  .custom-input {
    margin-bottom: 10px;
  }

  .add-product:hover {
    background-color: rgb(9, 235, 122);
  }
</style>

{% endblock %}



{% block body %}

<!-- <h3>Edit Product</h3> -->

{% for message in messages %}

<p style="color: green;">{{ message }}</p>

{% endfor %}

<div class="custom-container">
  <div style="width: 50%;">
    <img src="/media/{{ product.product_image }}" class="img-fluid" alt="Responsive image"
      style="display: block;margin: 0 auto;">

    <div class="text-center">
      <a href="{% url 'vendor_products' %}" class="btn btn-primary mx-auto" style="margin-top: 15px;">Go Back to
        Products</a>
    </div>

  </div>

  <div>
    <form class="w-75 mx-auto" action="{% url 'edit_product' product.get_absolute_url %}" method="post"
      enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-group row">
        <label for="product_name" class="col-sm-2 col-form-label">Product Name</label>
        <div class="col-sm-10">
          <input type="text" name="product_name" class="form-control custom-input" id="product_name"
            value="{{ product.product_name}}" required>
        </div>
      </div>  

      <div class="form-group row">
        <label for="product_price" class="col-sm-2 col-form-label">Price</label>
        <div class="col-sm-10">
          <input type="number" name="product_price" id="product_price" value="{{ product.product_price }}"
            class="form-control custom-input" min="1" required>
        </div>
      </div>

      <div class="form-group row">
        <label for="product_category" class="col-sm-2 col-form-label">Product Category</label>
        <div class="col-sm-10">
          <select name="product_category" id="product_category" class="form-control custom-input" required>
            <!--Add product category from ProductCategory models-->
            {% for category in categories %}

            <!--If condition to get the option selected by default-->
            <option value={{category.category }} {% if category.category == product.product_category.category %} selected
              {% endif %}>
              {{ category.category }}
            </option>


            {% endfor %}
          </select> <br>
        </div>
      </div>

      <div class="form-group row">
        <label for="product_detail" class="col-sm-2 col-form-label">Product Details</label>
        <div class="col-sm-10">
          <textarea type="text" name="product_detail" id="product_detail" cols="30" rows="10" class="form-control custom-input">{{ product.product_details }}</textarea>
        </div>
      </div>

      <div class="form-group row">
        <label for="id_product_image" class="col-sm-2 col-form-label">Product Image</label>
        <div class="col-sm-10">
          <input type="file" name="product_image" accept="image/*" id="id_product_image" class="form-control custom-input">
        </div>
      </div>

      <div class="form-group row">

        <div class="col-sm-10 " >
          <input type="submit" value="Update Product" class="form-control add-product custom-input">
        </div>
      </div>
    </form>
  </div>
</div>





<!-- <img src="/media/{{ product.product_image }}" style="display: block;"> -->



<!-- <form action="{% url 'edit_product' product.get_absolute_url %}" method="post" enctype="multipart/form-data">

        {% csrf_token %}
        <label for="product_name">Product Name</label>
        <input type="text" name="product_name" id="product_name" value="{{ product.product_name}}"> <br>

        <label for="product_price">Product Price</label>
        <input type="text" name="product_price" id="product_price" value="{{ product.product_price }}" > <br>
        
        <label for="product_category">Choose a Product Category:</label>
        {{ product.product_category }} -->
<!-- <select name="product_category"  id="product_category"> -->
<!--Add product category from ProductCategory models-->
<!-- {% for category in categories %} -->

<!--If condition to get the option selected by default-->
<!-- <option value={{category.category }} 
          {% if category.category == product.product_category.category %}
            selected
          {% endif %}>
          {{ category.category }}
          </option> 
            
                
         {% endfor %}
        </select> <br>

        <label for="product_detail">Product Details</label>
        <textarea name="product_detail" id="product_detail" cols="30" rows="10">{{ product.product_details }}</textarea> <br>

        <label for="id_product_image">Proudct Image</label>
          
        <input type="file" name="product_image" accept="image/*" id="id_product_image"> <br>

        <input type="submit" value="Add Product">

    </form> -->











{% endblock %}

templates/index.html
{% extends 'base.html' %}


{% block head %}

    <title>Vendor | Home</title>        

{% endblock %}


{% block body %}

   
    <h1 style="text-align: center; margin-top: 20%;">You have No order Yet:(</h1>
    
        

{% endblock %}

templates/nav_vendor.html
{% extends 'base.html' %}

{% block head %}

{% endblock %}


{% block nav %}


{% endblock %}



{% block body %}





{% endblock %}

templates/shop_orders.html
{% extends 'base.html' %}


{% block head %}

    <title>Vendor | Home</title>        

{% endblock %}


{% block body %}

   
<table class="table">
    <thead class="thead-light">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Product </th>
            <th scope="col">Quantity</th>
            <th scope="col">Phone number</th>
           
        </tr>
    </thead>

    <tbody>



        
        {% for order in orders %}
        <tr>
            <th scope="row" class="row-number"></th>
            <td>{{ order.product.product_name }}</td>
            <td class="product-quantity">{{ order.quantity }}</td>
            <td class="product-price">{{ order.user.mobile_number }}</td>
            

            <!--product.product.product_name-->
        </tr>

        {% endfor %}

        

    </tbody>
</table>
    
        <script>
             document.addEventListener("DOMContentLoaded", function () {

let rowElement = document.querySelectorAll(".row-number")

for (let i = 0; i < rowElement.length; i++) {
    rowElement[i].innerHTML = i + 1
}


})
        </script>

{% endblock %}

templates/update_shop_profile.html
{% extends 'base.html' %}


{% block head %}

<title>Vendor | Profile </title>

<style>
    body {
        background: rgb(99, 39, 120)
    }

    .form-control:focus {
        box-shadow: none;
        border-color: #BA68C8
    }

    .profile-button {
        background: rgb(99, 39, 120);
        box-shadow: none;
        border: none
    }

    .profile-button:hover {
        background: #682773
    }

    .profile-button:focus {
        background: #682773;
        box-shadow: none
    }

    .profile-button:active {
        background: #682773;
        box-shadow: none
    }

    .back:hover {
        color: #682773;
        cursor: pointer
    }

    .labels {
        font-size: 11px
    }

    .add-experience:hover {
        background: #BA68C8;
        color: #fff;
        cursor: pointer;
        border: solid 1px #BA68C8
    }
</style>



{% endblock %}





{% block body %}

<div class="container rounded bg-white mt-5 mb-5">
    <div class="row">
        <div class="col-md-3 border-right">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5"><img class=" mt-5" {% if shop.shop_image %} 
                src="/media/{{shop.shop_image}}" 
                {% endif %} style="max-width: 100%;"><span
                    class="font-weight-bold">Shop Name : <h3>{{ shop.shop_name }}</h3></span><span
                    class="text-black-50"></span><span>
                </span></div>
        </div>
        <div class="col-md-8 border-right">
            <div class="p-3 py-5">
                <form action="{% url 'vendor_profile' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <h4 class="text-right">Profile Settings</h4>
                    </div>
                    <div class="row mt-2">
                        <div class="col-md-12"><label class="labels">Shop name</label>
                            <input class="form-control" name="shop_name" value="{{ shop.shop_name }}">
                        </div>

                    </div>
                    <div class="row mt-3">
                        <div class="col-md-12"><label class="labels" for="mobile_number">Mobile Number</label><input
                                type="text" readonly class="form-control" name="mobile_number" id="mobile_number"
                                value="{{ shop.mobile_number }}"></div>



                        <div class="col-md-12"><label class="labels" for="password">Password</label><input
                                type="password" class="form-control" name="password" id="password"
                                value="{{ shop.password }}"></div>

                        <div class="col-md-12"><label class="labels" for="pincode">Pincode</label><input type="text"
                                class="form-control" name="pincode" id="pincode" value="{{ shop.pincode }}"></div>

                        <div class="row mt-3">
                            <div class="col-md-6"><label class="labels" for="shop_image">Shop image</label><input
                                    type="file" name="shop_image" class="form-control" accept="image/*" value=""></div>



                            <div class="mt-5 text-center">
                                <input type="submit" class="btn btn-primary profile-button" value="Update Profile">
                            </div>
                        </div>
                    </div>



                </form>

            </div>
        </div>
    </div>
</div>

<!-- <h1>Shop Profile</h1>
{% if shop.shop_image %}
<img src="/media/{{shop.shop_image}}" alt="">
{% endif %}

<form action="{% url 'vendor_profile' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <label for="shop_name">Shop Name</label>
    <input type="text" name="shop_name" id="shop_name" value="{{ shop.shop_name}}"> <br>

    <label for="mobile_number">Mobile Number</label>
    <input type="text" name="mobile_number" id="mobile_number" value="{{ shop.mobile_number }}"> <br>

    <label for="password">Password</label>
    <input type="password" name="password" id="password" value="{{ shop.password }}"> <br>

    <label for="pincode">Pincode</label>
    <input type="text" name="pincode" id="pincode" value="{{ shop.pincode }}"> <br>

    <label for="shop_image">Shop image</label>

    <input type="file" name="shop_image" id="shop_image"> <br>
    <input type="submit" value="Update Profile">
</form> -->

{% endblock %}

templates/vendor_product.html
{% extends 'base.html' %}


{% block head %}

<title>Vendor | Products</title>

<style>
 
  .card:hover {
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  }

</style>


{% endblock %}


{% block body %}


<div style="margin-top: 30px;">
    <div class="container">
        <div class="row">
            
                {% for product in products %}
                <div class="col-md-3">
                    <div class="card" style="width: 20rem;">
                      <img class="card-img-top" src="{{ media_url }}{{ product.product_image }}" alt="Card image" style="width:100%; height: 250px; object-fit: cover;">
                      <div class="card-body">
                        <h4 class="card-title">{{ product.product_name }}</h4>
                        <h6>Price : {{ product.product_price }} Rs</h6>
                        <h6>Product category : {{ product.product_category }}</h6>
                        <a href="{% url 'edit_product' product.get_absolute_url %}" class="btn btn-primary">Edit Product</a>
                      </div>
                    </div>
                  </div>

                  {% empty %}
                  <h1 style="text-align: center;">You have no products in shop  :( <a href="{% url 'add_product' %}">add product</a> </h1>
                {% endfor %}
    
            
        </div>
    </div>
    
</div>





  

{% endblock %}


<!-- <h1>{{ product.product_name }}</h1>
        <img src="{{ media_url }}{{ product.product_image }}" alt="">
        <ul>
            <li>{{ product.product_price }}</li>
            <li>{{ product.product_category }}</li>
            <li>{{ product.product_details }}</li>

        </ul> -->

<!-- <p>Test : {{ product.get_absolute_url}}</p> -->
<!-- <a href="{{ product.get_absolute_url }}">Edit Product</a> -->
<!-- <a href="{% url 'edit_product' product.get_absolute_url %}">Edit Product</a> -->